# Generated by Django 4.2.4 on 2023-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='inputText',
            field=models.TextField(default='default'),
        ),
    ]
